#!/bin/bash

set -e

GOBINARIES_ROOT=${GOBINARIES_ROOT-gobinari.es}
GOBINARIES_GIT_ORIGIN=https://github.com/motemen/gobinaries

root_dir=$(cd "$(dirname "$0")" && cd .. && pwd)

build_dir="$root_dir/public"
mkdir -p "$build_dir"

sources_dir="$root_dir/sources"

find "$sources_dir" -type f |
    while read -r s; do
        origin=$(head -1 "$s")
        name=${s#$sources_dir/}
        echo "--> $name	=> $origin" >&2
        case "$origin" in
            https://github.com/*/*/*)
                path=${origin#https://github.com/*/*/}
                remote=${origin/$path/}
                ./scripts/sync-remote-subtree "$remote" "$path"
                cat <<EOD > "$build_dir/$name"
<meta name="go-import" content="$GOBINARIES_ROOT git $GOBINARIES_GIT_ORIGIN">
EOD
            ;;

            https://github.com/*/*)
                cat <<EOD > "$build_dir/$name"
<meta name="go-import" content="$GOBINARIES_ROOT/$name git $origin">
EOD
            ;;

        esac
    done
