#!/bin/bash

set -e

o() {
    echo "$(basename "$0"): $*" >&2
}

remote=$1
path=$2
name=$(basename "$path")

o "fetching $remote"
git fetch --quiet "$remote"

o "checking out remote's $path at $name/"
treeish=$(git rev-parse "FETCH_HEAD:$path")
test "$(git cat-file -t "$treeish")" = "tree"
git rm -rf "$name/"
git read-tree -u --prefix="$name/" "$treeish"

if [ ! -e "$name/LICENSE" ] && git rev-parse --verify FETCH_HEAD:LICENSE > /dev/null 2>&1; then
    o "copying LICENSE to $name/"
    git cat-file blob FETCH_HEAD:LICENSE > "$name/LICENSE"
    git add "$name/LICENSE"
fi
